### ISSUE TITLE
Question about POD data

### ISSUE THREAD

**Issue by dvzubarev** [luispedro/diskhash#12]
Hi, thank you for this library.
I was trying to use c++ API of this library for this data: `key = uint32_t` and my value is 
``` 
struct temp_t {
    std::uint32_t    _cnt   =0 ;
    std::uint32_t    _cnt2 =0;
};
```
But it fails to compile, because of static_assert:
```   
 static_assert(std::is_pod<T>::value,
            "DiskHash only works for POD (plain old data) types that can be mempcy()ed around");
```
My struct is not `POD` because it has user-defined constructor. But, I believe it still can be memcpyed.
Maybe its better to replace  `std::is_pod` with `std::is_standard_layout`? What do you think? Also `is_pod` is deprecated in c++20.

**Comment by luispedro** [comment]
I think you're right, `std::is_pod` is too restrictive, but the right property is probably [std::is_trivially_copyable](http://www.cplusplus.com/reference/type_traits/is_trivially_copyable/).

Can you do a PR?
