### ISSUE TITLE
Python Unicode key

### ISSUE THREAD

**Issue by junghoocho** [luispedro/diskhash#7]
It seems that the package does not handle python Unicode string keys correctly.

For example, when I insert a Unicode key using the following code:
```python
import diskhash
tb = diskhash.StructHash("test.dht", 15, 'l', 'rw')
tb.insert("가", 1)
tb.lookup("가")
```
I get the correct value 1 in the same process where the (key, value) pair is inserted. But if I stop the python shell, restart a new python shell, and execute the following code:
```python
import diskhash
tb = diskhash.StructHash("test.dht", 15, 'l', 'r')
tb.lookup("가")
```
Nothing is returned from the code. I do not experience a similar problem if the key is an ASCII string.

My environment is:
- diskahash 0.0.4.0
- python 3.7 (anaconda)
- Ubuntu 18.04

**Comment by luispedro** [comment]
Thanks. This was indeed a bug for non-ASCII strings.

**Comment by junghoocho** [comment]
Wow, this was a quick fix. Thank you very much for the great package!

**Comment by luispedro** [comment]
The new version is up on pypi and includes this fix.
